"""add screen name

Revision ID: e5b065fca410
Revises: 27e9d06cf866
Create Date: 2020-08-13 02:44:37.096245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b065fca410'
down_revision = '27e9d06cf866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('screen_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'screen_name')
    # ### end Alembic commands ###
